Repository pbl-2018-hillclimb/burning-pro-client, pull requests merged in 2018-07, with the labels that each got.

#34 ImprudenceListActivityでリストがリセットされない不具合を修正
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/ImprudenceListActivity.java
Labels: bug, waiting for review

#36 デモに向けてアプリの体裁を整える
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/MainActivity.java
  app/src/main/res/layout/activity_imprudent_tweet.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/strings.xml
Labels: waiting for review

#37 Fix : ImprudentTweetActivityのUIの修正
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/ImprudentTweetActivity.java
  app/src/main/res/layout/activity_imprudent_tweet.xml
  app/src/main/res/values/strings.xml
Labels: waiting for review

#35 さくらのVPS側からデータを取得する
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/ImprudenceListActivity.java
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/JSONData.java
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/PhraseEntry.java
  app/src/main/res/values/strings.xml
Labels: waiting for review

#40 Place buttons so that spaces between buttons are equal
  app/src/main/res/layout/activity_imprudent_tweet.xml
Labels: UI, waiting for review

#43 [WIP] Save and restore textbox contents on display rotation
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/ImprudentTweetActivity.java
Labels: bug, difficulty/5, waiting for review
