Repository pbl-2018-hillclimb/burning-pro-client, pull requests merged in 2018-11, with the labels that each got.

#47 travis-CIからリリースapkをデプロイする
  .gitignore
  .travis.yml
  app/build.gradle
  secrets.tar.enc
Labels: difficulty/3, enhancement, task

#53 [Fix] 発言者情報のdisplay_name/twitterフィールドに関する修正
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/ImprudenceListActivity.java
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/PhraseEntry.java
Labels: bug, difficulty/1, task

#62 アプリを起動可能にする
  app/src/main/AndroidManifest.xml
Labels: bug, difficulty/3, task, waiting for review

#60 Add image resources for further use
  _resources/README.md
  _resources/burningpro-icon.svg
  _resources/burningpro-icon.svg-512x512.png
  _resources/forest-fire-1024x500.jpg
Labels: difficulty/2, enhancement, task

#64 Release v1.2
  _resources/README.md
  _resources/burningpro-icon.svg
  _resources/burningpro-icon.svg-512x512.png
  _resources/forest-fire-1024x500.jpg
  app/build.gradle
  app/src/main/AndroidManifest.xml
Labels: difficulty/1, task

#67 デバイスサイズに合わせたUI配置にする
  app/src/main/res/layout/activity_imprudent_tweet.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_registration.xml
Labels: UI, bug, waiting for review

#68 ヘッダーの部分の利用
  app/src/main/AndroidManifest.xml
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/ImprudenceListActivity.java
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/ImprudentTweetActivity.java
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/MainActivity.java
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/RegistrationActivity.java
  app/src/main/res/layout/activity_imprudence_list.xml
  app/src/main/res/layout/activity_imprudent_tweet.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_registration.xml
  app/src/main/res/values/strings.xml
Labels: UI, enhancement, waiting for review

#70 ローカルでのビルドが通るようにGradle・CIの設定を変える
  .gitignore
  .travis.yml
  app/build.gradle
  secrets.tar.enc
Labels: bug, difficulty/1, waiting for review

#73 一時的にRegistrationActivityへの遷移を無効にする
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/MainActivity.java
  app/src/main/res/layout/activity_main.xml
Labels: PBL item, UI, enhancement

#74 Release v1.3
  .gitignore
  .travis.yml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/ImprudenceListActivity.java
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/ImprudentTweetActivity.java
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/MainActivity.java
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/PostRequestTask.java
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/RegistrationActivity.java
  app/src/main/res/drawable/frame_style.xml
  app/src/main/res/layout/activity_imprudence_list.xml
  app/src/main/res/layout/activity_imprudent_tweet.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_registration.xml
  app/src/main/res/values/strings.xml
  secrets.tar.enc
Labels: difficulty/1, task

#75 Release v1.3.1
  app/build.gradle
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/ImprudentTweetActivity.java
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/MainActivity.java
  app/src/main/res/layout/activity_main.xml
Labels: difficulty/1, task

#79 Restore app name
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings.xml
Labels: bug, difficulty/1, task, waiting for review

#80 Release v1.3.2
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/strings.xml
Labels: difficulty/1, task, waiting for review

#84 デフォルトアイコンからの脱却
  .gitignore
  app/src/main/ic_launcher-web.png
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_foreground.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/ic_launcher_background.xml
Labels: difficulty/1, task, waiting for review

#82 ネットワークエラーで発言一覧が取得できなかった時のための機能追加
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/ImprudenceListActivity.java
  app/src/main/res/drawable-hdpi/ic_refresh_phrases.png
  app/src/main/res/drawable-mdpi/ic_refresh_phrases.png
  app/src/main/res/drawable-xhdpi/ic_refresh_phrases.png
  app/src/main/res/drawable-xxhdpi/ic_refresh_phrases.png
  app/src/main/res/menu/imprudence_list.xml
  app/src/main/res/values/strings.xml
Labels: PBL item, difficulty/3, enhancement, task

#86 Group phrases by person
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/ImprudenceListActivity.java
  app/src/main/res/layout/activity_imprudence_list.xml
Labels: UI, difficulty/5, enhancement, waiting for review

#85 いい発言追加申請のパラメータを変更
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/MainActivity.java
  app/src/main/java/jp/ac/titech/itpro/pbl/burning_pro/RegistrationActivity.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_registration.xml
Labels: enhancement, waiting for review
